# config/zedm_yaml
# Parameters for Stereolabs ZED mini camera
---

/**:
    ros__parameters:

        general:
            camera_model:               'zed2'
            camera_name:                'zed2'

        depth:
            min_depth:                  0.7             # Min: 0.2, Max: 3.0 - Default 0.7 - Note: reducing this value wil require more computational power and GPU memory
            max_depth:                  20.0            # Max: 40.0

        pos_tracking:
            imu_fusion:                 true            # enable/disable IMU fusion. When set to false, only the optical odometry will be used.
            publish_imu_tf:             true           # enable/disable the static IMU TF broadcasting

        sensors:
            sensors_timestamp_sync:     false           # Synchronize Sensors messages timestamp with latest received frame
            qos_history:        0                       # '0': KEEP_LAST - '1': KEEP_ALL
            qos_depth:          10                      # Queue size if using KEEP_LAST
            qos_reliability:    1                       # '0': BEST_EFFORT - '1': RELIABLE
            qos_durability:     1                       # '0': TRANSIENT_LOCAL - '1': VOLATILE

        object_detection:
            od_enabled:                 false           # True to enable Object Detection [only ZED 2]
            confidence_threshold:       50              # Minimum value of the detection confidence of an object [0,100]
            object_tracking_enabled:    true            # Enable/disable the tracking of the detected objects
            people_detection:           true            # Enable/disable the detection of persons
            vehicle_detection:          false           # Enable/disable the detection of vehicles
            qos_history:        0                       # '0': KEEP_LAST - '1': KEEP_ALL
            qos_depth:          10                      # Queue size if using KEEP_LAST
            qos_reliability:    1                       # '0': BEST_EFFORT - '1': RELIABLE
            qos_durability:     1                       # '0': TRANSIENT_LOCAL - '1': VOLATILE


