# config/zedm_yaml
# Parameters for Stereolabs ZED mini camera
---

/**:
    ros__parameters:

        general:
            camera_model:               'zedm'
            camera_name:                'zedm'

        depth:
            min_depth:                  0.35            # Min: 0.1, Max: 3.0 - Default 0.3 - Note: reducing this value wil require more computational power and GPU memory
            max_depth:                  10.0            # Max: 20.0

	pos_tracking:
            imu_fusion:                 true            # enable/disable IMU fusion. When set to false, only the optical odometry will be used.
            publish_imu_tf:             true

        sensors:
            sensors_image_sync:         false           # Synchronize Sensors messages with latest published video/depth message
            qos_history:                0               # '0': KEEP_LAST - '1': KEEP_ALL
            qos_depth:                  10              # Queue size if using KEEP_LAST
            qos_reliability:            1               # '0': BEST_EFFORT - '1': RELIABLE
            qos_durability:             1               # '0': TRANSIENT_LOCAL - '1': VOLATILE
