# config/zed2i_yaml
# Parameters for Stereolabs zed2i camera
---
/**:
    ros__parameters:
        general:
            camera_model: "zedx"
            camera_name: "zedx" # usually overwritten by launch file
            grab_resolution: 'HD1200' # The native camera grab resolution. 'HD1200', 'SVGA', 'AUTO'
            grab_frame_rate: 30 # ZED SDK internal grabbing rate (HD1200: 60 or 30 - SVGA: 120 or 60)

        depth:
            min_depth: 0.2 # Min: 0.2, Max: 3.0
            max_depth: 10.0 # Max: 40.0

